os2display/display-admin-client

src/components/util/image-uploader/image-uploader.jsx
src/components/util/image-uploader/image-uploader.scss
src/components/util/image-uploader/image.jsx
src/translations/da/common.json

AR-619: Image upload styling

---

src/components/edit-theme/edit-theme.jsx
src/components/util/color-picker/color-picker.jsx
src/components/util/color-picker/color-preview.jsx
src/translations/da/common.json

AR-619: Add sections and titles to theme edit

---

src/components/edit-playlist/edit-playlist.jsx
src/translations/da/common.json

AR-619: Add content sections and titles

---

src/components/media-list/media-list.jsx
src/components/media-list/media-list.scss
src/components/media-list/media-list.spec.js
src/components/util/search-box/search-box.spec.js
src/translations/da/common.json

AR-619: Style media-list

---

src/components/navigation/nav-items/nav-items.jsx
src/components/navigation/nav-items/nav-items.scss
src/components/navigation/sidebar/sidebar.jsx
src/components/navigation/sidebar/sidebar.scss

AR-619: Show active page in sidebar

---

src/components/util/list/list.jsx

AR-619: Add spacing to btns

---

src/components/playlist/playlist-create.jsx
src/components/playlist/playlist-form.jsx
src/components/playlist/playlist-list.jsx
src/components/screen/screen-form.jsx
src/components/slide/slide-form.jsx
src/components/slide/slides-list.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-637

AR-637: added toast and playlist list now deletes

---

src/components/slide/slide-create.jsx
src/components/slide/slide-edit.jsx
src/components/util/forms/form-input.jsx

https://jira.itkdev.dk/browse/AR-706
Converts number input values to numbers.

AR-707: Fixed number issue

---

src/components/util/forms/multiselect-dropdown/multi-dropdown.jsx

https://jira.itkdev.dk/browse/AR-739
Removed filter length requirement for dropdowns

AR-739: Removed filter length requirement for dropdowns

---

src/components/slide/slides-list.jsx
src/redux/api.js

https://jira.itkdev.dk/browse/AR-745
* Adds cache tags and validatesTags definitions for each redux toolkit api slice.
* Fixes delete issue with slides list.

AR-745: Added cache tags and invalidation

---

.docker/actions.config.json
.env
.github/workflows/pr.yml
docker-compose.actions.yml
docker-compose.yml
public/example_config.json

[Please add a link to the ticket being addressed by this change.](https://jira.itkdev.dk/browse/AR-746)
Use docker image for database with pre-load fixtures.
No screenshot.
No comments.

AR-746: Use database docker image

---

src/components/slide/content/media-selector.jsx
src/components/slide/slide-manager.jsx

https://jira.itkdev.dk/browse/AR-742
* Fixed issue where media fields could not be changed for a new file.
* Fixed translation of header in slide edit/create.

AR-742: Fixed issue with media edit

---

src/components/screen/grid-generation-and-select.jsx
src/components/screen/screen-form.jsx
src/components/util/forms/multiselect-dropdown/multi-dropdown.jsx
src/components/util/forms/multiselect-dropdown/multi-dropdown.scss

Remove header when there is no regions in layout: 
Remove checkbox on single-select:

AR-611: added 20 itemsperpage in screen layouts

---

src/components/util/forms/select.jsx
src/components/util/schedule/schedule-util.js
src/components/util/schedule/schedule.jsx

https://jira.itkdev.dk/browse/AR-692
* Enforces that weekno is only allowed for yearly freq  (page 43 - https://datatracker.ietf.org/doc/html/rfc5545)

AR-692: Only allow weekno option when yearly freq

---

src/components/playlist/playlist-create.jsx
src/components/playlist/playlist-edit.jsx
src/components/playlist/playlist-form.jsx
src/components/slide/slide-form.jsx
src/components/slide/slide-manager.jsx
src/components/util/forms/multiselect-dropdown/multi-dropdown.scss
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-762
* Adds publishing to playlists.

AR-762: Added publishing to playlists

---

src/components/util/forms/form-table/form-table.jsx
src/translations/da/common.json

AR-611: added helptext

---

src/components/util/multi-and-table/select-slides-table.jsx
src/translations/da/common.json

AR-611: switched api call

---

src/components/playlist/playlist-create.jsx

AR-611: playlist schedule

---

src/components/util/forms/multiselect-dropdown/multi-dropdown.jsx
src/components/util/list/list.jsx
src/components/util/search-box/search-box.jsx

AR-611: corrected some errors

---

src/components/slide/content/feed-selector.jsx
src/components/slide/content/multiselect-from-endpoint.jsx
src/components/slide/slide-form.jsx

https://jira.itkdev.dk/browse/AR-768
Fixed issues with MultiselectFromEndpoint needed for sparkle.io integration.

AR-768: Fixed issues with MultiselectFromEndpoint

---

src/components/util/published.jsx

https://jira.itkdev.dk/browse/AR-786
Fixed calculation of published.

AR-786: Fixed published calculation

---

src/components/screen-list/campaign-icon.jsx
src/components/screen/screen-list.jsx

AR-611: fixed error on screen list

---

src/components/slide/content/content-form.jsx
src/components/slide/preview/remote-component-helper.jsx
src/components/slide/preview/remote-component-wrapper.jsx
src/components/slide/slide-form.jsx
src/components/slide/slide-manager.jsx
src/components/util/forms/multiselect-dropdown/playlists/playlists-dropdown.jsx
src/translations/da/common.json

- Move config import into another file, to avoid doing it every time something changes.
- fix duration component 
- Remove preview header

AR-611: fixed duration component and jumping  preview

---

src/components/playlist-drag-and-drop/playlist-drag-and-drop.jsx
src/components/playlist/campaign-form.jsx
src/components/playlist/playlist-campaign-form.jsx
src/components/screen/screen-form.jsx
src/components/slide/content/content-form.jsx
src/components/slide/slide-form.jsx
src/components/util/forms/form-checkbox.jsx
src/components/util/forms/form-input.jsx
src/components/util/forms/multiselect-dropdown/multi-dropdown.jsx
src/components/util/forms/rich-text/rich-text.jsx
src/components/util/forms/select.jsx
src/components/util/list/link-for-list.jsx
src/components/util/multi-and-table/select-groups-table.jsx
src/components/util/multi-and-table/select-playlists-table.jsx
src/components/util/multi-and-table/select-screens-table.jsx
src/components/util/multi-and-table/select-slides-table.jsx
src/translations/da/common.json

AR-611: add edit button and get more data

---

src/components/slide/content/content-form.jsx
src/components/slide/content/file-selector.jsx
src/components/slide/content/media-selector-modal.jsx
src/components/slide/preview/remote-component-wrapper.jsx

AR-611: image fix

---

.github/workflows/pr.yml

Removed cypress github actions tests until they are fixed.

AR-764: Removed github actions until it is fixed

---

README.md
package.json

Please add a link to the ticket being addressed by this change.

AR-720: added some documentation

---

src/components/slide/content/file-selector.jsx

https://jira.itkdev.dk/browse/AR-435
Fixed file selector widget with regards to adding and removing files.

AR-435: Fixed file selector

---

.env
docker-compose.yml

https://jira.itkdev.dk/browse/AR-716
Remove test container

AR-716: remove test container

---

src/components/user/login.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-718

AR-718: added value check

---

src/components/slide/content/feed-selector.jsx
src/redux/api/api.generated.js
src/redux/api/api.generated.ts
src/redux/api/api.json

https://jira.itkdev.dk/browse/AR-802
Added filtering to feed sources.

AR-802: Added filtering to get feed sources call

---

README.md

https://jira.itkdev.dk/browse/AR-631
Moved documentation to display-docs.

AR-631: Moved documentation to display-docs

---

docker-compose.yml
src/components/slide/content/multiselect-from-endpoint.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-796
Added error message when fetching feed config fails.
Added http to https redirect to docker setup

AR-796: Added error message for multiselect-from-endpoint

---

src/redux/api/api.generated.ts
src/redux/api/api.json

generated api. only .ts as the changes does not affect .js

AR-611: api.json with order(createdat) for groups

---

docker-compose.server.yml
infrastructure/etc/confd/templates/config.tmpl

https://jira.itkdev.dk/browse/AR-821
Add server config for APP_TOUCH_BUTTON_REGIONS

AR-821: Added APP_TOUCH_BUTTON_REGIONS to server config

---

.github/workflows/docker_build_develop.yml
.github/workflows/docker_build_main.yml
.github/workflows/docker_build_tag.yml

https://jira.itkdev.dk/browse/AR-797
Updated docker build with prod images.

AR-797: Added docker image builds for main and tags

---

cypress.json
docker-compose.yml
src/App.spec.js
src/components/groups/group.spec.js
src/components/groups/groups-list.spec.js
src/components/media/media-list.spec.js
src/components/media/media.spec.js
src/components/navigation/sidebar/sidebar.spec.js
src/components/navigation/topbar/top-bar.spec.js
src/components/playlist/campaign.spec.js
src/components/playlist/playlist-list.spec.js
src/components/playlist/playlist.spec.js
src/components/playlist/shared-list.spec.js
src/components/screen/screen-list.spec.js
src/components/screen/screen.spec.js
src/components/slide/slide.spec.js
src/components/slide/slides-list.spec.js
src/components/themes/theme.spec.js
src/components/themes/themes-list.spec.js
src/components/user/login.spec.js
src/components/util/paginate/pagination.spec.js
src/components/util/table/table-body.spec.js
src/components/util/table/table-header.spec.js
src/components/util/table/table.spec.js
src/context/modal-context/info-modal.spec.js

Reverted tests and used baseurl instead

added cypress baseurl reverted tests

---

src/components/media-modal/media-modal.jsx
src/components/slide/content/content-form.jsx
src/components/slide/content/station/station-selector.jsx
src/components/slide/slide-form.jsx
src/components/util/forms/multiselect-dropdown/multi-dropdown.jsx
src/components/util/forms/rich-text/rich-text.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/ARREJS-14
https://www.figma.com/proto/QZHEvDBpV3031nn90hr38B/%5BRejseplanen%5D-Slide-template?page-id=0%3A1&node-id=8%3A94&viewport=302%2C48%2C0.5&scaling=contain&starting-point-node-id=1%3A2

ARREJS-14: Rejseplan in admin

---

src/components/slide/slide-manager.jsx
src/components/util/multi-and-table/select-playlists-table.jsx
src/components/util/multi-and-table/select-screens-table.jsx

https://jira.itkdev.dk/browse/AR-544
mapped some values that changed in the api

AR-544: fix errors cb shared playlist changes

---

src/components/slide/content/multiselect-from-endpoint.jsx
src/components/slide/content/poster-selector.jsx
src/redux/dynamic-base-query.js

https://jira.itkdev.dk/browse/AR-837
Adds tenant to calls from multiselect-from-endpoint.

AR-837: Added tenant to multiselect-from-endpoint

---

src/components/themes/themes-columns.jsx
src/components/themes/themes-list.jsx

https://jira.itkdev.dk/browse/AR-836
Changed onSlides to onNumberOfSlides

AR-836: Changed onSlides to onNumberOfSlides

---

src/error-boundary.jsx
src/error-boundary.scss

https://jira.itkdev.dk/browse/AR-829
Changed class names to lower case.

AR-829: Lower cased class names

---

src/components/slide/preview/remote-component-wrapper.jsx

https://jira.itkdev.dk/browse/AR-842
Added slide class to remote component

AR-842: Added slide class to remote component

---

src/components/slide/content/content-form.jsx

https://jira.itkdev.dk/browse/AR-857

AR-857: change default duration from 10 to 15

---

src/components/screen/screen-create.jsx
src/components/screen/screen-form.jsx
src/components/screen/screen-manager.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-860
add dropdown for resolution/orientation on screen
remove screen width/height

AR-859: add resolution and orientation

---

.docker/vhost.conf
docker-compose.server.yml
docker-compose.yml
infrastructure/Dockerfile
infrastructure/docker-entrypoint.sh
infrastructure/etc/confd/templates/default.conf.tmpl
infrastructure/etc/confd/templates/nginx.conf.tmpl
infrastructure/run.sh

https://jira.itkdev.dk/browse/AR-875
Updated docker setup to match new itkdev base setup
N/A
N/A

Docker update

---

src/components/media/image-list.jsx
src/components/media/media-list.jsx
src/components/playlist/playlist-gantt-chart.jsx
src/components/screen/util/screen-gantt-chart.jsx
src/components/themes/theme-form.jsx
src/components/themes/theme-manager.jsx
src/components/util/gantt-chart.jsx
src/components/util/helpers/selectedHelper.jsx

The media library did not work, has not worked for a while, I think it was refactored some time ago, so I fixed that.
The css was not displayed in the theme page (create/edit)
Now, shared playlists in gantt are not clickable/do not redirect

AR-873: correct link in gantt + misc

---

src/components/util/forms/multiselect-dropdown/tenants/tenants-dropdown.jsx
src/components/util/multi-and-table/select-screens-table.jsx

Please add a link to the ticket being addressed by this change.

AR-889: search in screens

---

CHANGELOG.md
docker-compose.yml

https://jira.itkdev.dk/browse/AR-900

add 8080 to port

---

CHANGELOG.md
src/components/navigation/nav-items/nav-items.jsx
src/components/navigation/nav-items/nav-items.scss

https://jira.itkdev.dk/browse/AR-899
- disable menu links
- add some styling

AR-899: disable active menu link (and add styling)

---

CHANGELOG.md
src/components/media/media-list.jsx
src/components/media/media-list.scss
src/components/proptypes/column-proptypes.jsx
src/components/slide/content/file-selector.jsx
src/components/slide/content/media-selector-modal.jsx
src/components/slide/slide-form.jsx
src/components/slide/slide-manager.jsx
src/context/modal-context/delete-modal.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-898
Now possible to delete media from slide and sort media list

AR-898: now possible to delete media

---

CHANGELOG.md
src/components/media-modal/media-modal.jsx
src/components/media/image-list.jsx
src/components/media/media-list.jsx
src/components/themes/theme-form.jsx
src/components/themes/theme-manager.jsx
src/components/util/image-uploader/image-uploader.jsx

no ticket
change selected image to use hook
save logo: if theme has a logo and is saved, it now saves with said logo. before it saved "nothing" and removed the logo.

media uploader and logo upload theme

---

CHANGELOG.md
src/app.jsx
src/components/slide/content/file-dropzone.jsx
src/components/slide/content/file-selector.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/AR-907
* Adds information about max file sizes.

AR-907: Added information about max file sizes

---

CHANGELOG.md
src/components/util/forms/rich-text/rich-text.jsx

https://jira.itkdev.dk/browse/AR-932
* Changed rich text defaultValue to avoid update loops.
* Cleaned up rich text toolbar options.

AR-932: Rich text fixes.

---

CHANGELOG.md
LICENSE

https://jira.itkdev.dk/browse/AR-925
Added license.

AR-925: Added license

---

CHANGELOG.md
src/config-loader.js

https://jira.itkdev.dk/browse/AR-951
Added config loader optimization to avoid competing promises.

AR-951: Added config loader optimization to avoid competing promises

---

CHANGELOG.md
src/components/playlist/campaign.spec.js
src/components/playlist/playlist.spec.js

https://jira.itkdev.dk/browse/DISPLAY-964
Readd and fix cypress tests
n/a

DISPLAY-964: readd test, up specificity of get req

---

CHANGELOG.md
src/components/screen/screen-manager.jsx

https://jira.itkdev.dk/browse/DISPLAY-927
It does not redirect before it saves the playlists anymore
N/A

DISPLAY-927: add length check on playlisttoadd

---

CHANGELOG.md
package.json
src/components/screen/util/screen-gantt-chart.jsx
src/components/util/schedule/schedule-util.js
src/components/util/schedule/schedule.jsx
yarn.lock

https://jira.itkdev.dk/browse/SUPP0RT-922
Changed to handling rrule dates as UTC

SUPPORT-922: Changed to handling rrule dates as UTC

---

CHANGELOG.md
src/components/playlist-drag-and-drop/playlist-drag-and-drop.jsx
src/components/playlist/campaign-form.jsx
src/components/playlist/playlist-form.jsx
src/components/slide/content/poster-selector.jsx
src/components/util/drag-and-drop-table/drag-and-drop-table.jsx
src/components/util/forms/multiselect-dropdown/pagination-button.jsx
src/components/util/multi-and-table/select-groups-table.jsx
src/components/util/multi-and-table/select-playlists-table.jsx
src/components/util/multi-and-table/select-screens-table.jsx
src/components/util/multi-and-table/select-slides-table.jsx
src/components/util/table/table.jsx
src/context/modal-context/info-modal.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/SUPP0RT-993 (not possible to view for people outside itkdev)
Paginate multidropdowns selected values

SUPP0RT-993: add pagination to tables below dropdown

---

CHANGELOG.md
src/components/playlist-drag-and-drop/playlist-drag-and-drop.jsx
src/components/playlist/campaign-form.jsx
src/components/playlist/playlist-form.jsx
src/components/slide/content/poster-selector.jsx
src/components/util/drag-and-drop-table/drag-and-drop-table.jsx
src/components/util/forms/multiselect-dropdown/pagination-button.jsx
src/components/util/multi-and-table/select-groups-table.jsx
src/components/util/multi-and-table/select-playlists-table.jsx
src/components/util/multi-and-table/select-screens-table.jsx
src/components/util/multi-and-table/select-slides-table.jsx
src/components/util/table/table.jsx
src/context/modal-context/info-modal.jsx
src/translations/da/common.json

Please add a link to the ticket being addressed by this change.

Hotfix pagination

---

CHANGELOG.md
src/components/slide/content/feed-selector.jsx
src/components/slide/content/poster-selector.jsx
src/translations/da/common.json

https://jira.itkdev.dk/browse/DISPLAY-947
N/A
N/A

DISPLAY-947: Updated poster and feed selection

---

infrastructure/docker-entrypoint.sh

ITKDev: Fixed nginx entry script

---

.github/workflows/docker_build_develop.yml
.github/workflows/docker_build_tag.yml
.github/workflows/github_build_release.yml
.github/workflows/pr.yml
CHANGELOG.md
infrastructure/Dockerfile
infrastructure/run.sh
public/example_config.json

https://jira.itkdev.dk/browse/DISPLAY-986
* Update docker build to publish to "os2display" org on docker hup.
* Update github workflow to latest actions.
* Add github workflow to build and create release.
* Change `example_config.json` to use relative paths.
N/A

DISPLAY-986: Update docker build and github workflows

---

CHANGELOG.md
public/example_release.json

N/A
Added example_release.json file

DISPLAY-986: Added example_release.json file

---

.github/workflows/itkdev_docker_build_tag.yml
.github/workflows/os2display_docker_build_tag.yml
CHANGELOG.md

https://jira.itkdev.dk/browse/DISPLAY-986
Fix version not set in release.json

DISPLAY-986: Fix version not set in release.json

---

CHANGELOG.md
src/components/user/login.jsx
src/components/user/login.scss

Please add a link to the ticket being addressed by this change.

DISPLAY-1028: color of background

---

CHANGELOG.md
docker-compose.yml
public/manifest.json
src/components/user/login.jsx
src/components/user/oidc-login.jsx
src/index.js
src/translations/da/common.json

https://jira.itkdev.dk/browse/DISPLAY-993
Fixed OIDC login buttons.
Depends on changes in https://github.com/os2display/display-api-service/pull/163

Fixed OIDC login buttons

---

CHANGELOG.md

https://jira.itkdev.dk/browse/DISPLAY-1039
- [#210](https://github.com/os2display/display-admin-client/pull/210)
Use thumbnails for media list if they are set
N/A

DISPLAY-1039: Release 1.4.0

---

CHANGELOG.md
src/components/user/login.jsx
src/index.js

Code authorization flow

---

CHANGELOG.md
src/redux/api.js

https://jira.itkdev.dk/browse/SUPP0RT-1328
Fixed caching issues when adding/removing playlists from slide

Fixed caching issues when adding/removing playlists from slide

---

CHANGELOG.md
src/components/themes/theme-form.jsx
src/components/themes/theme-manager.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/369
Changed how theme logo is loaded following change in API.

#369: Changed how theme logo is loaded

---

CHANGELOG.md
src/components/activation-code/activation-code-activate.jsx
src/components/user/login.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/394
* Fixed body of activate request.

#394: Fixed body of activate request

---

CHANGELOG.md
src/components/media-modal/media-modal.jsx
src/components/slide/content/media-selector-list.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/970
Fixed issue when clicking media archive element when media archive is not in multiple mode.

970: Fixed media archive click issue

---

CHANGELOG.md
src/redux/api/api.generated.ts
src/redux/api/package.json

https://leantime.itkdev.dk/#/tickets/showTicket/964
Removed caching from redux toolkit api

964: Removed caching from redux toolkit api

---

CHANGELOG.md
src/components/slide/preview/remote-component-wrapper.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/398
Fixed how theme is set following change in API.

Fixed how theme is set for slide preview

---

CHANGELOG.md
src/components/slide/content/station/station-selector.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/2221
Fixed rejseplanen component so it does not throw errors when searching for stops.

2221: Fixed rejseplanen component

---

CHANGELOG.md
src/components/screen/screen-form.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/2484
* Fixed is vertical check

Fixed is vertical check

---

CHANGELOG.md

https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/2773
Release 2.1.0

2773: Release 2.1.0

---

.docker/vhost.conf
CHANGELOG.md
infrastructure/itkdev/etc/confd/templates/default.conf.tmpl
infrastructure/os2display/etc/confd/templates/default.conf.tmpl

https://leantime.itkdev.dk/dashboard/show?tab=ticketdetails#/tickets/showTicket/2773
- Add no-cache directive

2773: Add no-cache directive

---

CHANGELOG.md

https://leantime.itkdev.dk/dashboard/show?tab=ticketdetails#/tickets/showTicket/2773
Release 2.1.1

2773: Release 2.1.1

---

CHANGELOG.md
src/components/feed-sources/templates/calendar-api-feed-type.jsx

https://leantime.itkdev.dk/#/tickets/showTicket/2331
Fixed calendar api feed source config endpoint.

Fixed calendar api feed source config endpoint
